/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsystem;
import javax.swing.JOptionPane;
import java.time.LocalDate;
//import net.sourceforge.plantuml.project.time.Month;

/**
 *
 * @author Hope
 */
public class HomePage extends javax.swing.JFrame {

	/**
	 * Creates new form HomePage
	 */
	public HomePage() {
		initComponents();
		this.setLocationRelativeTo(null);
		LocalDate dateToday=LocalDate.now();
//		Month month=Month.JUNE;
//		String monthNow=month.toString();
//		monthField.setText(monthNow);
		int date=dateToday.getDayOfMonth();
		String dateNow=Integer.toString(date);
		dateField.setText(dateNow);
		
	}
	public void DefaultLanguage(String languagePreffered){
		if(languagePreffered.equalsIgnoreCase("Urdu")){
			adminLabel.setText("ایڈمین");
			adminLoginPageButton.setText("یہاں کلک کریں");
			userLabel.setText("ممبر");
			userLoginPageButton.setText("یہاں کلک کریں");
			quoteField.setText("کوئی مذہب انسانیت سے بڑھ کر نہں َ");
			personalityNameField.setText("عبد الاستار ایدھی");
			monthField.setText("جون");
		}
	}
	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        adminLabel = new javax.swing.JLabel();
        adminLoginPageButton = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
        userLoginPageButton = new javax.swing.JButton();
        languageSelector = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        quoteField = new javax.swing.JLabel();
        personalityNameField = new javax.swing.JLabel();
        monthField = new javax.swing.JLabel();
        dateField = new javax.swing.JLabel();
        yearField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(0, 153, 153));
        adminLabel.setText("Admin");
        jPanel6.add(adminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 85, -1, 30));

        adminLoginPageButton.setBackground(new java.awt.Color(0, 51, 51));
        adminLoginPageButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        adminLoginPageButton.setForeground(new java.awt.Color(0, 153, 153));
        adminLoginPageButton.setText("Click here");
        adminLoginPageButton.setToolTipText("Click here to get in if you are admin.");
        adminLoginPageButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray));
        adminLoginPageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminLoginPageButton.setFocusPainted(false);
        adminLoginPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginPageButtonActionPerformed(evt);
            }
        });
        jPanel6.add(adminLoginPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 144, 107, 35));

        userLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 153, 153));
        userLabel.setText("User");
        jPanel6.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 239, -1, 30));

        userLoginPageButton.setBackground(new java.awt.Color(0, 51, 51));
        userLoginPageButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        userLoginPageButton.setForeground(new java.awt.Color(0, 153, 153));
        userLoginPageButton.setText("Click here");
        userLoginPageButton.setToolTipText("Click here to get in if you are user.");
        userLoginPageButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray));
        userLoginPageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userLoginPageButton.setFocusPainted(false);
        userLoginPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLoginPageButtonActionPerformed(evt);
            }
        });
        jPanel6.add(userLoginPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 295, 102, 35));

        languageSelector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_menu_40px.png"))); // NOI18N
        languageSelector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        languageSelector.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                languageSelectorMouseMoved(evt);
            }
        });
        languageSelector.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                languageSelectorFocusGained(evt);
            }
        });
        jPanel6.add(languageSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 30, 30));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 360));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_sort_down_20px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 0, 19, 25));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_cancel_20px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 0, 19, 25));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 570, 40));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/managementsystem/icons8_nature_care_120px.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 250, 320));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        quoteField.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        quoteField.setForeground(new java.awt.Color(0, 102, 102));
        quoteField.setText("No Religion is bigger than Humanity.");
        quoteField.setToolTipText("");
        jPanel1.add(quoteField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, 40));

        personalityNameField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        personalityNameField.setForeground(new java.awt.Color(0, 102, 102));
        personalityNameField.setText("~ Abdul Sattar Edhi");
        jPanel1.add(personalityNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, 20));

        monthField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        monthField.setForeground(new java.awt.Color(0, 51, 51));
        monthField.setText("December");
        jPanel1.add(monthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 20));

        dateField.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        dateField.setForeground(new java.awt.Color(0, 51, 51));
        dateField.setText("95");
        jPanel1.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 60, 50));

        yearField.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        yearField.setForeground(new java.awt.Color(0, 51, 51));
        yearField.setText("2020");
        jPanel1.add(yearField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 320, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userLoginPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLoginPageButtonActionPerformed
        // TODO add your handling code here:
		new managementsystem.LoginPage().setVisible(true);
		this.dispose();
    }//GEN-LAST:event_userLoginPageButtonActionPerformed

    private void adminLoginPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginPageButtonActionPerformed
        // TODO add your handling code here:
		AdminLoginPage getIn=new AdminLoginPage();
		getIn.setVisible(true);
		dispose();
    }//GEN-LAST:event_adminLoginPageButtonActionPerformed

    private void languageSelectorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_languageSelectorMouseMoved
        // TODO add your handling code here:

    }//GEN-LAST:event_languageSelectorMouseMoved

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
		int close=JOptionPane.showConfirmDialog(this, "Leave the page?","Leaving the page" , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
		if(close==JOptionPane.YES_OPTION){
			System.exit(0);
		}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setState(HomePage.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void languageSelectorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_languageSelectorFocusGained
        // TODO add your handling code here:
		DefaultLanguage("Urdu");
    }//GEN-LAST:event_languageSelectorFocusGained

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new HomePage().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JButton adminLoginPageButton;
    private javax.swing.JLabel dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel languageSelector;
    private javax.swing.JLabel monthField;
    private javax.swing.JLabel personalityNameField;
    private javax.swing.JLabel quoteField;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton userLoginPageButton;
    private javax.swing.JLabel yearField;
    // End of variables declaration//GEN-END:variables
}
