/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JobsHere;


/**
 *
 * @author Hope
 */
public class AddandEditJobs extends javax.swing.JFrame {
	private String currentUser;

	/**
	 * Creates new form AddandEditJobs
	 */
	public AddandEditJobs(){
		initComponents();
		this.setLocationRelativeTo(null);
	}
	public AddandEditJobs(String currentUser) {
		initComponents();
		this.currentUser=currentUser;
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        facebook = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        instagram = new javax.swing.JLabel();
        logOutButton = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addHospitalPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        addClinicPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        addWaterPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        addTreePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        addAmbulancePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        addNursePanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fireBrigadePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        employeePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        orphanHousePanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        addEmployPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        addDoctorPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        transgenderPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        removeUserPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        organHousePanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        showUserPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_menu_40px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel3MouseMoved(evt);
            }
        });

        facebook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_facebook_circled_40px.png"))); // NOI18N
        facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facebook.setMinimumSize(new java.awt.Dimension(0, 40));

        twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_twitter_40px.png"))); // NOI18N
        twitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitter.setMinimumSize(new java.awt.Dimension(0, 40));

        instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_instagram_40px.png"))); // NOI18N
        instagram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instagram.setMinimumSize(new java.awt.Dimension(0, 40));

        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_logout_rounded_up_25px.png"))); // NOI18N
        logOutButton.setToolTipText("Log Out");
        logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButton.setMinimumSize(new java.awt.Dimension(0, 40));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(facebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instagram, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(facebook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(twitter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instagram, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 540));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addHospitalPanel.setBackground(new java.awt.Color(255, 255, 255));
        addHospitalPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addHospitalPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addHospitalPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addHospitalPanelMouseMoved(evt);
            }
        });
        addHospitalPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addHospitalPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addHospitalPanelMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_hospital_60px.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 153, 153));
        jLabel22.setText("Add Hospital");

        javax.swing.GroupLayout addHospitalPanelLayout = new javax.swing.GroupLayout(addHospitalPanel);
        addHospitalPanel.setLayout(addHospitalPanelLayout);
        addHospitalPanelLayout.setHorizontalGroup(
            addHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addHospitalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addHospitalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addHospitalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        addHospitalPanelLayout.setVerticalGroup(
            addHospitalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addHospitalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(addHospitalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 100));

        addClinicPanel.setBackground(new java.awt.Color(255, 255, 255));
        addClinicPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addClinicPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addClinicPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addClinicPanelMouseMoved(evt);
            }
        });
        addClinicPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClinicPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addClinicPanelMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_clinic_60px.png"))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 153, 153));
        jLabel26.setText("Add Clinic");

        javax.swing.GroupLayout addClinicPanelLayout = new javax.swing.GroupLayout(addClinicPanel);
        addClinicPanel.setLayout(addClinicPanelLayout);
        addClinicPanelLayout.setHorizontalGroup(
            addClinicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addClinicPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(addClinicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addClinicPanelLayout.setVerticalGroup(
            addClinicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addClinicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26))
        );

        jPanel2.add(addClinicPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 100, -1));

        addWaterPanel.setBackground(new java.awt.Color(255, 255, 255));
        addWaterPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addWaterPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addWaterPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addWaterPanelMouseMoved(evt);
            }
        });
        addWaterPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addWaterPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addWaterPanelMouseExited(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_water_60px_1.png"))); // NOI18N

        jLabel28.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 153, 153));
        jLabel28.setText("Add Water");

        javax.swing.GroupLayout addWaterPanelLayout = new javax.swing.GroupLayout(addWaterPanel);
        addWaterPanel.setLayout(addWaterPanelLayout);
        addWaterPanelLayout.setHorizontalGroup(
            addWaterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWaterPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addWaterPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addContainerGap())
        );
        addWaterPanelLayout.setVerticalGroup(
            addWaterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addWaterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel28))
        );

        jPanel2.add(addWaterPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        addTreePanel.setBackground(new java.awt.Color(255, 255, 255));
        addTreePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addTreePanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addTreePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addTreePanelMouseMoved(evt);
            }
        });
        addTreePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addTreePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addTreePanelMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_treehouse_60px.png"))); // NOI18N

        jLabel29.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 153, 153));
        jLabel29.setText("Add Plantation");

        javax.swing.GroupLayout addTreePanelLayout = new javax.swing.GroupLayout(addTreePanel);
        addTreePanel.setLayout(addTreePanelLayout);
        addTreePanelLayout.setHorizontalGroup(
            addTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTreePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(addTreePanelLayout.createSequentialGroup()
                .addComponent(jLabel29)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        addTreePanelLayout.setVerticalGroup(
            addTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTreePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(16, 16, 16))
        );

        jPanel2.add(addTreePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 100, 100));

        addAmbulancePanel.setBackground(new java.awt.Color(255, 255, 255));
        addAmbulancePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addAmbulancePanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addAmbulancePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addAmbulancePanelMouseMoved(evt);
            }
        });
        addAmbulancePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAmbulancePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addAmbulancePanelMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_ambulance_60px.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("Add Ambulance");

        javax.swing.GroupLayout addAmbulancePanelLayout = new javax.swing.GroupLayout(addAmbulancePanel);
        addAmbulancePanel.setLayout(addAmbulancePanelLayout);
        addAmbulancePanelLayout.setHorizontalGroup(
            addAmbulancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAmbulancePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addAmbulancePanelLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        addAmbulancePanelLayout.setVerticalGroup(
            addAmbulancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAmbulancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(addAmbulancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 110, 100));

        addNursePanel.setBackground(new java.awt.Color(255, 255, 255));
        addNursePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addNursePanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addNursePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addNursePanelMouseMoved(evt);
            }
        });
        addNursePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNursePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addNursePanelMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_nurse_60px.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 153, 153));
        jLabel27.setText("Add Nurse");

        javax.swing.GroupLayout addNursePanelLayout = new javax.swing.GroupLayout(addNursePanel);
        addNursePanel.setLayout(addNursePanelLayout);
        addNursePanelLayout.setHorizontalGroup(
            addNursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNursePanelLayout.createSequentialGroup()
                .addGroup(addNursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNursePanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addNursePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        addNursePanelLayout.setVerticalGroup(
            addNursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27))
        );

        jPanel2.add(addNursePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        fireBrigadePanel.setBackground(new java.awt.Color(255, 255, 255));
        fireBrigadePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fireBrigadePanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        fireBrigadePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fireBrigadePanelMouseMoved(evt);
            }
        });
        fireBrigadePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireBrigadePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fireBrigadePanelMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_fire_truck_60px_1.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 153));
        jLabel24.setText("Add Firebrigade");

        javax.swing.GroupLayout fireBrigadePanelLayout = new javax.swing.GroupLayout(fireBrigadePanel);
        fireBrigadePanel.setLayout(fireBrigadePanelLayout);
        fireBrigadePanelLayout.setHorizontalGroup(
            fireBrigadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fireBrigadePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(fireBrigadePanelLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        fireBrigadePanelLayout.setVerticalGroup(
            fireBrigadePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fireBrigadePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(fireBrigadePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 110, 100));

        employeePanel.setBackground(new java.awt.Color(255, 255, 255));
        employeePanel.setToolTipText("Current Employies");
        employeePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        employeePanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        employeePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                employeePanelMouseMoved(evt);
            }
        });
        employeePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeePanelMouseExited(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_employee_60px.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 153, 153));
        jLabel33.setText("Employees");

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel33)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel33))
        );

        jPanel2.add(employeePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 100, -1));

        orphanHousePanel.setBackground(new java.awt.Color(255, 255, 255));
        orphanHousePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        orphanHousePanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        orphanHousePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                orphanHousePanelMouseMoved(evt);
            }
        });
        orphanHousePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orphanHousePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orphanHousePanelMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_warehouse_60px.png"))); // NOI18N

        jLabel34.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 153, 153));
        jLabel34.setText("Orphan H.");

        javax.swing.GroupLayout orphanHousePanelLayout = new javax.swing.GroupLayout(orphanHousePanel);
        orphanHousePanel.setLayout(orphanHousePanelLayout);
        orphanHousePanelLayout.setHorizontalGroup(
            orphanHousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orphanHousePanelLayout.createSequentialGroup()
                .addGroup(orphanHousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orphanHousePanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(orphanHousePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel34)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        orphanHousePanelLayout.setVerticalGroup(
            orphanHousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orphanHousePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel34)
                .addGap(1, 1, 1))
        );

        jPanel2.add(orphanHousePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        addEmployPanel.setBackground(new java.awt.Color(255, 255, 255));
        addEmployPanel.setToolTipText("Add Employ");
        addEmployPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addEmployPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addEmployPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addEmployPanelMouseMoved(evt);
            }
        });
        addEmployPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEmployPanelMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_add_user_group_woman_man_60px.png"))); // NOI18N

        jLabel35.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 153, 153));
        jLabel35.setText("Add Empl.");

        javax.swing.GroupLayout addEmployPanelLayout = new javax.swing.GroupLayout(addEmployPanel);
        addEmployPanel.setLayout(addEmployPanelLayout);
        addEmployPanelLayout.setHorizontalGroup(
            addEmployPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addContainerGap())
        );
        addEmployPanelLayout.setVerticalGroup(
            addEmployPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35))
        );

        jPanel2.add(addEmployPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        addDoctorPanel.setBackground(new java.awt.Color(255, 255, 255));
        addDoctorPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addDoctorPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        addDoctorPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addDoctorPanelMouseMoved(evt);
            }
        });
        addDoctorPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addDoctorPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addDoctorPanelMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_stethoscope_60px.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 153, 153));
        jLabel25.setText("Add Doctor");

        javax.swing.GroupLayout addDoctorPanelLayout = new javax.swing.GroupLayout(addDoctorPanel);
        addDoctorPanel.setLayout(addDoctorPanelLayout);
        addDoctorPanelLayout.setHorizontalGroup(
            addDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDoctorPanelLayout.createSequentialGroup()
                .addGroup(addDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addDoctorPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addDoctorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        addDoctorPanelLayout.setVerticalGroup(
            addDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addDoctorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25))
        );

        jPanel2.add(addDoctorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 100, -1));

        transgenderPanel.setBackground(new java.awt.Color(255, 255, 255));
        transgenderPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transgenderPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        transgenderPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                transgenderPanelMouseMoved(evt);
            }
        });
        transgenderPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transgenderPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transgenderPanelMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_transgender_60px.png"))); // NOI18N

        jLabel30.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 153, 153));
        jLabel30.setText("Trans House");

        javax.swing.GroupLayout transgenderPanelLayout = new javax.swing.GroupLayout(transgenderPanel);
        transgenderPanel.setLayout(transgenderPanelLayout);
        transgenderPanelLayout.setHorizontalGroup(
            transgenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transgenderPanelLayout.createSequentialGroup()
                .addGroup(transgenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transgenderPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transgenderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel30)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transgenderPanelLayout.setVerticalGroup(
            transgenderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transgenderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30))
        );

        jPanel2.add(transgenderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, 100));

        removeUserPanel.setBackground(new java.awt.Color(255, 255, 255));
        removeUserPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeUserPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        removeUserPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                removeUserPanelMouseMoved(evt);
            }
        });
        removeUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeUserPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                removeUserPanelMouseExited(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_remove_administrator_60px.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 153, 153));
        jLabel31.setText("Remove User");

        javax.swing.GroupLayout removeUserPanelLayout = new javax.swing.GroupLayout(removeUserPanel);
        removeUserPanel.setLayout(removeUserPanelLayout);
        removeUserPanelLayout.setHorizontalGroup(
            removeUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeUserPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(removeUserPanelLayout.createSequentialGroup()
                .addComponent(jLabel31)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        removeUserPanelLayout.setVerticalGroup(
            removeUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31))
        );

        jPanel2.add(removeUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 100, -1));

        organHousePanel.setBackground(new java.awt.Color(255, 255, 255));
        organHousePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        organHousePanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        organHousePanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                organHousePanelMouseMoved(evt);
            }
        });
        organHousePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                organHousePanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                organHousePanelMouseExited(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_lungs_60px.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 153, 153));
        jLabel36.setText("Organ H.");

        javax.swing.GroupLayout organHousePanelLayout = new javax.swing.GroupLayout(organHousePanel);
        organHousePanel.setLayout(organHousePanelLayout);
        organHousePanelLayout.setHorizontalGroup(
            organHousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organHousePanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(organHousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        organHousePanelLayout.setVerticalGroup(
            organHousePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(organHousePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel36))
        );

        jPanel2.add(organHousePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, 100));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel18MouseMoved(evt);
            }
        });
        jPanel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel18MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel18MouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_pharmacy_60px.png"))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 153, 153));
        jLabel37.setText("Pharmacy");
        jLabel37.setToolTipText("Click to add Pharmacy Details");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel37)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel37))
        );

        jPanel2.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 100, -1));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel19.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel19MouseMoved(evt);
            }
        });
        jPanel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel19MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel19MouseExited(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_upload_to_cloud_60px.png"))); // NOI18N

        jLabel38.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 153, 153));
        jLabel38.setText(" Uploading");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel38))
        );

        jPanel2.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setToolTipText("Click to add Help Line detaisl");
        jPanel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel20.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel20.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel20MouseMoved(evt);
            }
        });
        jPanel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel20MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel20MouseExited(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_help_60px.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 153, 153));
        jLabel39.setText(" Help Line");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel39)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel39))
        );

        jPanel2.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        showUserPanel.setBackground(new java.awt.Color(255, 255, 255));
        showUserPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        showUserPanel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        showUserPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                showUserPanelMouseMoved(evt);
            }
        });
        showUserPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showUserPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                showUserPanelMouseExited(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_client_management_60px.png"))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Traditional Arabic", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 153, 153));
        jLabel32.setText("Show User");

        javax.swing.GroupLayout showUserPanelLayout = new javax.swing.GroupLayout(showUserPanel);
        showUserPanel.setLayout(showUserPanelLayout);
        showUserPanelLayout.setHorizontalGroup(
            showUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showUserPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, showUserPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addContainerGap())
        );
        showUserPanelLayout.setVerticalGroup(
            showUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(showUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel32))
        );

        jPanel2.add(showUserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 850, 510));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_sort_down_20px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JobsHere/AdminImages/icons8_cancel_20px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(782, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 850, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
		new managementsystem.HomePage().setVisible(true);
		this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
		this.setState(AddandEditJobs.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseMoved
        // TODO add your handling code here:
		
    }//GEN-LAST:event_jLabel3MouseMoved

    private void addHospitalPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addHospitalPanelMouseClicked
        // TODO add your handling code here:
		new AddHospital(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addHospitalPanelMouseClicked

    private void addAmbulancePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAmbulancePanelMouseClicked
        // TODO add your handling code here:
		new AddAmbulance(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addAmbulancePanelMouseClicked

    private void fireBrigadePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireBrigadePanelMouseClicked
        // TODO add your handling code here:
		new AddFireBrigade(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_fireBrigadePanelMouseClicked

    private void addDoctorPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDoctorPanelMouseClicked
        // TODO add your handling code here:
		new AddDoctor(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addDoctorPanelMouseClicked

    private void addNursePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNursePanelMouseClicked
        // TODO add your handling code here:
		new AddNurse(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addNursePanelMouseClicked

    private void addWaterPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addWaterPanelMouseClicked
        // TODO add your handling code here:
		new AddWater(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addWaterPanelMouseClicked

    private void addClinicPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClinicPanelMouseClicked
        // TODO add your handling code here:
		new AddClinic(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addClinicPanelMouseClicked

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
		new managementsystem.AdminLoginPage().setVisible(true);
		this.dispose();
		
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void showUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUserPanelMouseClicked
        // TODO add your handling code here:
		new managementsystem.showUser(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_showUserPanelMouseClicked

    private void removeUserPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeUserPanelMouseClicked
        // TODO add your handling code here:
		new managementsystem.RemoveUser(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_removeUserPanelMouseClicked

    private void addTreePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTreePanelMouseClicked
        // TODO add your handling code here:
		new TreeFoundation(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addTreePanelMouseClicked

    private void employeePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_employeePanelMouseClicked

    private void transgenderPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transgenderPanelMouseClicked
        // TODO add your handling code here:
		new TransHouse(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_transgenderPanelMouseClicked

    private void orphanHousePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orphanHousePanelMouseClicked
        // TODO add your handling code here:
		new SweetHomes(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_orphanHousePanelMouseClicked

    private void addEmployPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployPanelMouseClicked
        // TODO add your handling code here:
		new AddEmployess(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_addEmployPanelMouseClicked

    private void organHousePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organHousePanelMouseClicked
        // TODO add your handling code here:
		new AddOrgan(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_organHousePanelMouseClicked

    private void jPanel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseClicked
        // TODO add your handling code here:
		new Pharmacy(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_jPanel18MouseClicked

    private void jPanel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseClicked
        // TODO add your handling code here:
		new UnderConstructionSites(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_jPanel19MouseClicked

    private void jPanel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseClicked
        // TODO add your handling code here:
		new HelpLine(currentUser).setVisible(true);
		this.dispose();
    }//GEN-LAST:event_jPanel20MouseClicked

    private void addHospitalPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addHospitalPanelMouseMoved
        // TODO add your handling code here:
		addHospitalPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
    }//GEN-LAST:event_addHospitalPanelMouseMoved

    private void addHospitalPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addHospitalPanelMouseExited
        // TODO add your handling code here:
		addHospitalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addHospitalPanelMouseExited

    private void addAmbulancePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAmbulancePanelMouseMoved
        // TODO add your handling code here:
		addAmbulancePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_addAmbulancePanelMouseMoved

    private void addAmbulancePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAmbulancePanelMouseExited
        // TODO add your handling code here:
		addAmbulancePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addAmbulancePanelMouseExited

    private void fireBrigadePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireBrigadePanelMouseMoved
        // TODO add your handling code here:
		fireBrigadePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_fireBrigadePanelMouseMoved

    private void fireBrigadePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireBrigadePanelMouseExited
        // TODO add your handling code here:
		fireBrigadePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_fireBrigadePanelMouseExited

    private void addDoctorPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDoctorPanelMouseMoved
        // TODO add your handling code here:
		addDoctorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
    }//GEN-LAST:event_addDoctorPanelMouseMoved

    private void addDoctorPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDoctorPanelMouseExited
        // TODO add your handling code here:
		addDoctorPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addDoctorPanelMouseExited

    private void addClinicPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClinicPanelMouseMoved
        // TODO add your handling code here:
		addClinicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_addClinicPanelMouseMoved

    private void addClinicPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClinicPanelMouseExited
        // TODO add your handling code here:
		addClinicPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addClinicPanelMouseExited

    private void addNursePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNursePanelMouseMoved
        // TODO add your handling code here:
		addNursePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_addNursePanelMouseMoved

    private void addNursePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNursePanelMouseExited
        // TODO add your handling code here:
		addNursePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addNursePanelMouseExited

    private void addWaterPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addWaterPanelMouseMoved
        // TODO add your handling code here:
		addWaterPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_addWaterPanelMouseMoved

    private void addWaterPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addWaterPanelMouseExited
        // TODO add your handling code here:
		addWaterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addWaterPanelMouseExited

    private void addTreePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTreePanelMouseMoved
        // TODO add your handling code here:
		addTreePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_addTreePanelMouseMoved

    private void addTreePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addTreePanelMouseExited
        // TODO add your handling code here:
		addTreePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addTreePanelMouseExited

    private void employeePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelMouseMoved
        // TODO add your handling code here:
		employeePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_employeePanelMouseMoved

    private void employeePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePanelMouseExited
        // TODO add your handling code here:
		employeePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_employeePanelMouseExited

    private void transgenderPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transgenderPanelMouseMoved
        // TODO add your handling code here:
		transgenderPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_transgenderPanelMouseMoved

    private void transgenderPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transgenderPanelMouseExited
        // TODO add your handling code here:
		transgenderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_transgenderPanelMouseExited

    private void orphanHousePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orphanHousePanelMouseMoved
        // TODO add your handling code here:
		orphanHousePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_orphanHousePanelMouseMoved

    private void orphanHousePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orphanHousePanelMouseExited
        // TODO add your handling code here:
		orphanHousePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_orphanHousePanelMouseExited

    private void addEmployPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployPanelMouseMoved
        // TODO add your handling code here:
		addEmployPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_addEmployPanelMouseMoved

    private void addEmployPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployPanelMouseExited
        // TODO add your handling code here:
		addEmployPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_addEmployPanelMouseExited

    private void organHousePanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organHousePanelMouseMoved
        // TODO add your handling code here:
		organHousePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_organHousePanelMouseMoved

    private void organHousePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organHousePanelMouseExited
        // TODO add your handling code here:
		organHousePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_organHousePanelMouseExited

    private void showUserPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUserPanelMouseMoved
        // TODO add your handling code here:
		showUserPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
    }//GEN-LAST:event_showUserPanelMouseMoved

    private void showUserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showUserPanelMouseExited
        // TODO add your handling code here:
		showUserPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_showUserPanelMouseExited

    private void removeUserPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeUserPanelMouseMoved
        // TODO add your handling code here:
		removeUserPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_removeUserPanelMouseMoved

    private void removeUserPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeUserPanelMouseExited
        // TODO add your handling code here:
		removeUserPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_removeUserPanelMouseExited

    private void jPanel18MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseMoved
        // TODO add your handling code here:
		jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_jPanel18MouseMoved

    private void jPanel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel18MouseExited
        // TODO add your handling code here:
		jPanel18.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jPanel18MouseExited

    private void jPanel19MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseMoved
        // TODO add your handling code here:
		jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_jPanel19MouseMoved

    private void jPanel19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel19MouseExited
        // TODO add your handling code here:
		jPanel19.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jPanel19MouseExited

    private void jPanel20MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseMoved
        // TODO add your handling code here:
		jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,153,153)));
    }//GEN-LAST:event_jPanel20MouseMoved

    private void jPanel20MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel20MouseExited
        // TODO add your handling code here:
		jPanel20.setBorder(javax.swing.BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_jPanel20MouseExited

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddandEditJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddandEditJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddandEditJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddandEditJobs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
        //</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddandEditJobs().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addAmbulancePanel;
    private javax.swing.JPanel addClinicPanel;
    private javax.swing.JPanel addDoctorPanel;
    private javax.swing.JPanel addEmployPanel;
    private javax.swing.JPanel addHospitalPanel;
    private javax.swing.JPanel addNursePanel;
    private javax.swing.JPanel addTreePanel;
    private javax.swing.JPanel addWaterPanel;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JLabel facebook;
    private javax.swing.JPanel fireBrigadePanel;
    private javax.swing.JLabel instagram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logOutButton;
    private javax.swing.JPanel organHousePanel;
    private javax.swing.JPanel orphanHousePanel;
    private javax.swing.JPanel removeUserPanel;
    private javax.swing.JPanel showUserPanel;
    private javax.swing.JPanel transgenderPanel;
    private javax.swing.JLabel twitter;
    // End of variables declaration//GEN-END:variables
}
